### ISSUE TITLE
Ajouter Emilie

### ISSUE THREAD

**Issue by adriens** [adriens/livre-or-collaborateurs-glia-slideshow#10]
# Prérequis

1 - Prendre connaissance du README
2 - Prendre connaissance du code de conduite pour contribuer cf `CONTRIBUTING.md`

**Comment by adriens** [comment]
Section déployée cf https://github.com/adriens/livre-or-collaborateurs-glia-slideshow/pull/22

**Comment by adriens** [comment]
Good Job @meilie389 ça a de la gueule 👏 
Penses à apporter ta tablette cette semaine, ce sera utile pour présenter au mieux tes slides 👍

**Comment by meilie389** [comment]
Ok super merci
Et ça marche pour la tablette 👍

**Comment by adriens** [comment]
😎
