### ISSUE TITLE
:bug: Jane DO avant Romain

### ISSUE THREAD

**Issue by adriens** [adriens/livre-or-collaborateurs-glia-slideshow#101]
# :grey_question: About

JANE DO est avant le slide de Romain : ça devrait être le contraire.

![image](https://github.com/opt-nc/livre-or-collaborateurs-glia-slideshow/assets/5235127/6bfdd168-68be-41ed-b24f-643e6a764b61)

# :dart: Actions

Dans l'ordre des slides, mettre [`Jane Doe`](https://opt-nc.github.io/livre-or-collaborateurs-glia-slideshow/#/9) après [`Romain PELIZZO`](https://opt-nc.github.io/livre-or-collaborateurs-glia-slideshow/#/10)

**Comment by Draks898** [comment]
Si je comprend bien "Jane DOE" c'est un exemple, elle doit toujours être en dernier c'est ça ?

**Comment by Draks898** [comment]
voilà @adriens problème réglé.
![image](https://github.com/opt-nc/livre-or-collaborateurs-glia-slideshow/assets/103997763/4ebbb181-e4bb-468b-b6ef-9a0ef810a4e6)
![image](https://github.com/opt-nc/livre-or-collaborateurs-glia-slideshow/assets/103997763/be5ac386-1c7a-464f-af47-42bff0d5e2c1)

**Comment by adriens** [comment]
Je teste

**Comment by adriens** [comment]
:ok_hand:
