### ISSUE TITLE
🥳 Ajouter Daniel SANTOS au livre d'or des contributeurs du GLIA 🥇 

### ISSUE THREAD

**Issue by adriens** [adriens/livre-or-collaborateurs-glia-slideshow#52]
# Prérequis

1 - Prendre connaissance du README
2 - Prendre connaissance du code de conduite pour contribuer cf `CONTRIBUTING.md`

# Contexte

Daniel SANTOS aka. [Dougniel](https://github.com/Dougniel) a rejoitn le bureau depuis quelques mois et a eu l'occasion de contributer sur de nombreux domaines tels que : 

- désendettement et modernisation d'applications
- développement de nouvelles fonctionnalités
- innovation (partenaires mobilis, pilote GH)

Le corpus des contributions étant désromais conséquent, il est temps d'ajouter Daniel à notre livre d'Or.

# Action

- [ ] En respectant les guidelines de la repo, enrichir avec la partie de Daniel

**Comment by Dougniel** [comment]
oh là 
![image](https://user-images.githubusercontent.com/39691264/146284511-82b1ba8d-0911-4fa2-b18d-79f7b8b631ac.png)
Je vais essayer d'upgrader les dépendances

**Comment by adriens** [comment]
> Je vais essayer d'upgrader les dépendances

TOP !

**Comment by Dougniel** [comment]
@adriens , je n'ai pas le droit de pusher une nouvelle branche pour faire ma PR

**Comment by Dougniel** [comment]
@adriens, c'est bon la PR est prête https://github.com/adriens/livre-or-collaborateurs-glia-slideshow/pull/53

**Comment by adriens** [comment]
@Dougniel  y'a une toute petite douille mineure (une image impossible à loader) : 

![image](https://user-images.githubusercontent.com/5235127/146607307-0fabebae-cbcf-49e4-bf46-a969efade076.png)

**Comment by Dougniel** [comment]
@adriens , nouvelle PR https://github.com/adriens/livre-or-collaborateurs-glia-slideshow/pull/55

**Comment by adriens** [comment]
Dernière typo 
![image](https://user-images.githubusercontent.com/5235127/146693581-003a86fd-f829-4d5f-8105-06b488b15a54.png)

**Comment by Dougniel** [comment]
@adriens, c'est corrigé https://github.com/adriens/livre-or-collaborateurs-glia-slideshow/pull/57

**Comment by adriens** [comment]
Mergé et déployé #58
