### ISSUE TITLE
Demande et ajout d'un avatar pour Jimmy Avae sur son slide

### ISSUE THREAD

**Issue by spencer-forrest-opt** [adriens/livre-or-collaborateurs-glia-slideshow#64]
# Prérequis

1 - Prendre connaissance du README
2 - Prendre connaissance du code de conduite pour contribuer cf `CONTRIBUTING.md`

# Issue description

[Jimmy Avae](https://adriens.github.io/livre-or-collaborateurs-glia-slideshow/#/2/1) n'a pas d'avatar dans le slideshow: [Error 404](https://adriens.github.io/livre-or-collaborateurs-glia-slideshow/img/javae/avatar_rnd.png)

<img width="640" alt="Jimmy_Avae_1" src="https://user-images.githubusercontent.com/104797863/167346227-f521fe30-b76e-4ee7-bbc8-38c756bc92eb.png">
<img width="640" alt="Jimmy_Avae_2" src="https://user-images.githubusercontent.com/104797863/167346260-ce10f850-10b4-4d98-b5ac-a68be15075db.png">

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/167358817-31674e9b-18b5-4155-95c9-86318eabddc1.png)

**Comment by zYmMiJ** [comment]
cf : https://github.com/adriens/livre-or-collaborateurs-glia-slideshow/pull/72

**Comment by adriens** [comment]
Mergé sur toutes les branches.

**Comment by adriens** [comment]
merci @zJimmyz pour le patch 🙏

**Comment by spencer-forrest-opt** [comment]
@zYmMiJ @adriens 

Works great ! 

![Jimmy](https://user-images.githubusercontent.com/104797863/168913005-1c7481ca-58ae-4e95-b978-1274fa4736a2.png)

**Comment by adriens** [comment]
Excellent, merci pour le test @spencer-forrest-opt 👐
