### ISSUE TITLE
Style sheet link missing for the contributor 'dsantos'

### ISSUE THREAD

**Issue by spencer-forrest-opt** [adriens/livre-or-collaborateurs-glia-slideshow#67]
# Problem

- Contributor @Dougniel: 
  His style sheet (see:`style.css`) in his `index.html` ▶️ depends on an other contributor ◀️  style sheet, potentially more than one.

  ▶️ (Might be an indirect violation of the game rule: `On the touche pas aux slides des autres collaborateurs: "chacun sa colonne"`)

<img width="1680" alt="slide" src="https://user-images.githubusercontent.com/104797863/167950322-2882de96-ef30-47be-839e-8d57855fd585.png">
<img width="433" alt="dsantos" src="https://user-images.githubusercontent.com/104797863/167823785-adc1bc4a-7ce2-4c87-86f2-e5b057bfcbd0.png">
<img width="837" alt="index" src="https://user-images.githubusercontent.com/104797863/167823830-6ebae572-da9d-441d-8365-c5f38355355d.png">
  
# Potential solution

1. Link his `style.css` to the root `index.html`
2. Make sure his `class` and `id` names in his `style.css` are different than the other contributors' in order to not interfere with their style

**Comment by Dougniel** [comment]
Bien vu @spencer-forrest-opt, merci pour ce retour

Je ne comprends pas ce qui s'est passé car j'avais fait ce code, mais j'ai du m'embrouiller entre le fork et les branches de mon fork :
<img width="1455" alt="image" src="https://user-images.githubusercontent.com/39691264/168013077-46333d25-80f9-4182-acb6-2baec0854133.png">

**Comment by adriens** [comment]
> Je ne comprends pas ce qui s'est passé car j'avais fait ce code, mais j'ai du m'embrouiller entre le fork et les branches de mon fork :

@Dougniel : ça marchait.... sur ton poste :grey_question: :trollface: :rofl:

**Comment by Dougniel** [comment]
> > Je ne comprends pas ce qui s'est passé car j'avais fait ce code, mais j'ai du m'embrouiller entre le fork et les branches de mon fork :
> 
> @Dougniel : ça marchait.... sur ton poste ❔ :trollface: 🤣

En fait non, en regardant davantage j'avais bien tout mergé et j'ai bien oublié la ligne que @spencer-forrest-opt. Par contre je n'ai pas vu de bug particulier

**Comment by Dougniel** [comment]
Intéressant, avant ça marchait 🤔  : 
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/39691264/168015195-d581ee7d-6d14-42e0-86c1-104a8fe0f906.png">

Qu'est-ce qu'ils ont bien pu faire pour qu'une lib écrite en Javascript ait une dépendance par rapport au type de processeur

**Comment by adriens** [comment]
> Qu'est-ce qu'ils ont bien pu faire pour qu'une lib écrite en Javascript ait une dépendance par rapport au type de processeur

:laughing: :rofl: :hankey:

**Comment by spencer-forrest-opt** [comment]
Might be linked #69
