### ISSUE TITLE
Missing logo on the 'Innovation' slide

### ISSUE THREAD

**Issue by spencer-forrest-opt** [adriens/livre-or-collaborateurs-glia-slideshow#69]
# Problem

Missing logo on one for @Dougniel's slide.

https://adriens.github.io/livre-or-collaborateurs-glia-slideshow/#/7/9

![innovation](https://user-images.githubusercontent.com/104797863/168179668-caa26173-33e5-4951-b8a6-7609e5802498.png)

**Comment by Dougniel** [comment]
Merci @spencer-forrest-opt, j'ai un peu bâclé les tests on dirait 😅

**Comment by adriens** [comment]
Il est implacable @spencer-forrest-opt 🕵️‍♂️
