### ISSUE TITLE
:arrow_up:  Upgrade  reveal.js to `v5` latest release

### ISSUE THREAD

**Issue by adriens** [adriens/livre-or-collaborateurs-glia-slideshow#71]
# :grey_question: Contexte

Le slideshow des collaborateurs du GLIA poursuit sa vie au gré des collaborations, chaque collaborateur apportant sa petite touche d'originalité/créatvité , cf ajout récent[ des slides de Romain Pelizzo](https://opt-nc.github.io/livre-or-collaborateurs-glia-slideshow/#/9)

- https://github.com/opt-nc/livre-or-collaborateurs-glia-slideshow/pull/99

De mon côté, je l'utilise parfois lorsque je suis en rendez-vous à l'extérieur du bureau, c'est à la fois très pratique et très esthétique.... et je l'utiliserai prochainement pour présenter le bureau.

Dans le même temps, `reveal.js`:

- [reveal.js 5.0 is out 🚀](https://twitter.com/hakimel/status/1718960945920418008)
- est maintenu et poursuit ses montées de versions, par exemple avec la release récente de la [`5.0.5`](https://github.com/hakimel/reveal.js/releases/tag/5.0.5)
- les libs Js doivent être montées (cf PR #98 et #97)

# :dart: Actions

:point_right: Le but de cette issue est d'upgrader Reveal dans sa [latest release](https://github.com/hakimel/reveal.js/releases/latest)

# :heavy_check_mark: DoD

- [x] Framework à jour
- [x] Slideshow fonctionnel
- [x] Description d'éventuelles nouvelles features en SCRUM
- [ ] PRs fermées

**Comment by adriens** [comment]
Fixera : 

- https://github.com/opt-nc/livre-or-collaborateurs-glia-slideshow/pull/98
- https://github.com/opt-nc/livre-or-collaborateurs-glia-slideshow/pull/97

**Comment by ThomDeveo** [comment]
## Montée de version de reveal.js vers release `5.1.0` ✔ 

![Image](https://github.com/user-attachments/assets/ff5c33ef-4227-496c-b7f9-f37001cdbb15)

- commande 
```sh
npm run start
```

- réponse 
```sh
> reveal.js@5.1.0 start
> grunt serve

Running "connect:server" (connect) task
(node:50854) [DEP0044] DeprecationWarning: The `util.isArray` API is deprecated. Please use `Array.isArray()` instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Started connect web server on http://localhost:8000

Running "watch" task
Waiting...

```

**Comment by ThomDeveo** [comment]
# What's new ? 

## 5.0.0 

- scroll view ( une petite bar verticale qui nous guide sur l'avancement de scroll des diapositive) 

## 5.1.0 

-  Possibilité de mettre une video en arrière plan qui ne s'arrête pas pendant le scroll des différentes slides
- Une nouvelle classe `enter-fullscreen` peut être ajoutée à n’importe quel élément de la présentation (comme une image, une vidéo, ou même un texte). Lorsque qu'un clic est effectué sur cet élément, il passera automatiquement en plein écran.

**Comment by ThomDeveo** [comment]
Ajout de la "scroll view" :

![Image](https://github.com/user-attachments/assets/9007ee2e-3343-4f33-835d-633c19605f4f)


⚠ On perd le défilement avec plusieurs colonnes. Toutes les sections sont les unes à la suite des autres 
=> changement de structure
