### ISSUE TITLE
HTTP link to the website does not work - HTTP 404

### ISSUE THREAD

**Issue by spencer-forrest-opt** [adriens/livre-or-collaborateurs-glia-slideshow#83]
![acceder au site](https://user-images.githubusercontent.com/104797863/203868706-f399eb28-c705-4bb5-b451-890a40a13d22.png)

[http://bit.ly/2TBXHq1](https://bit.ly/3lgS8Zb) redirects to [https://adriens.github.io/livre-or-collaborateurs-glia-slideshow/#/](https://adriens.github.io/livre-or-collaborateurs-glia-slideshow/#/)

![404](https://user-images.githubusercontent.com/104797863/203868903-49ceddb6-0344-48ca-b8ba-88b9ff880e4c.png)

**Comment by mbarre** [comment]
c'est corrigé, je te laisse faire la review @spencer-forrest-opt 
https://github.com/opt-nc/livre-or-collaborateurs-glia-slideshow/pull/85
